classdef AboutDialog < handle
%
%
%                 ================================================
%                            Autor: Jorge De Los Santos       
%                        E-mail: delossantosmfq@gmail.com        
%                      Blog : http://matlab-typ.blogspot.mx      
%                                     Rev 0.0.1                   
%                                 Fecha: 20/10/2014
%                 ================================================
    
    properties
        hDlg;
        name_;
        version_;
        description_;
        authors_;
        email_;
        web_;
    end
    
    methods
        function obj = AboutDialog(name,version,description,authors,email,web)
            if isa(version,'double')
                version = num2str(version);
            end
            obj.name_ = name;
            obj.version_ = version;
            obj.description_ = description;
            obj.authors_ = authors;
            obj.email_ = email;
            obj.web_ = web;
            obj.initComponents();
        end
        
        function initComponents(obj)
            obj.hDlg = figure('MenuBar','None',...
                'NumberTitle','off',...
                'Name','About ...',...
                'Position',[0 0 300 150],...
                'Color','w',...
                'Resize','off');
            centerfig(obj.hDlg);
            
            uicontrol('style','text',...
                'String',[obj.name_,' ',obj.version_],...
                'Units','Normalized',...
                'Position',[0 0.85 1 0.12],...
                'FontName','DejaVu Sans Mono',...
                'FontSize',11,...
                'ForegroundColor','b',...
                'FontWeight','bold');
            
            uicontrol('style','text',...
                'String',obj.description_,...
                'Units','Normalized',...
                'Position',[0 0.4 1 0.42]);
            
            uicontrol('style','text',...
                'String',obj.authors_,...
                'Units','Normalized',...
                'Position',[0 0.25 1 0.1],...
                'FontWeight','bold',...
                'ForegroundColor',ones(1,3)*0.4);
            
            uicontrol('style','text',...
                'String',obj.email_,...
                'Units','Normalized',...
                'Position',[0 0.15 1 0.1],...
                'ForegroundColor',ones(1,3)*0.4);
            
%             [~,hweb]=javacomponent({'javax.swing.JLabel',obj.web_},[],obj.hDlg);
%             set(hweb,'Units','Normalized',...
%                 'Position',[0 0.5 1 0.1])
            uicontrol('style','text',...
                'String',obj.web_,...
                'Units','Normalized',...
                'Position',[0 0.05 1 0.1],...
                'ForegroundColor',ones(1,3)*0.4);
            
            set(findobj('Style','text'),'BackG',get(obj.hDlg,'Color'));
        end
    end
    
end

