classdef Canvas < uimoon.core.EComponent
    % CANVAS
    
    properties
    end
    
    methods
        function obj = Canvas()
            obj.hUI = uipanel('BackgroundColor','w',...
                'Units','Pixels');
            p_pos = get(obj.hUI,'Position');
            obj.hEUI = axes('Parent',obj.hUI,...
                'NextPlot','Add',...
                'XTick',[],'YTick',[],...
                'Units','Normalized',...
                'Position',[0 0 1 1],...
                'Visible','off',...
                'XLim',[0 p_pos(3)],...
                'YLim',[0 p_pos(4)]);
        end
    end
end

